backend:
  name: github
  repo: Falcao1303/geektopiapg
  branch: master

auth_backend:
  name: auth0
  domain: geektopiapg.us.auth0.com
  client_id: 'RoMqeBMmHKq1yRnEd3mMlIC7XPRsbMl5'  # Copie o client_id da nova aplicação criada (Geektopia CMS Web)

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "edicoes"
    label: "Edições Anteriores"
    folder: "edicoes-anteriores"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título da Edição", name: "title", widget: "string"}
      - {label: "Data do Evento", name: "date", widget: "datetime"}
      - {label: "Local", name: "local", widget: "string"}
      - {label: "Público", name: "publico", widget: "string"}
      - {label: "Atrações", name: "atracoes", widget: "list"}
      - {label: "Descrição", name: "body", widget: "markdown"}
      - {label: "Imagem Principal", name: "imagem", widget: "image"}
